"""Aumentar longitud del campo DNI de Docente a 15

Revision ID: 2ce0dbe58b0b
Revises: d8389cca1e0d
Create Date: 2025-10-28 09:53:39.783935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce0dbe58b0b'
down_revision = 'd8389cca1e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
