"""Versión inicial de la base de datos

Revision ID: d8389cca1e0d
Revises: 
Create Date: 2025-10-28 09:04:07.840919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8389cca1e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('programas',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('total_creditos', sa.Integer(), nullable=True),
    sa.Column('total_horas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('caracteristicas', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=True),
    sa.Column('dni', sa.String(length=6), nullable=True),
    sa.Column('celular', sa.String(length=9), nullable=True),
    sa.Column('correo_personal', sa.String(length=120), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('programa_estudio', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad_competencia', sa.String(length=120), nullable=True),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('horas_teoricas', sa.Integer(), nullable=True),
    sa.Column('horas_practicas', sa.Integer(), nullable=True),
    sa.Column('contenidos', sa.Text(), nullable=True),
    sa.Column('sesiones_programadas', sa.Integer(), nullable=True),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiantes_info',
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('contacto_parentesco', sa.String(length=50), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto_nombre_2', sa.String(length=120), nullable=True),
    sa.Column('contacto_parentesco_2', sa.String(length=50), nullable=True),
    sa.Column('contacto_telefono_2', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('estudiante_id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_matricula', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', 'modulo_id', 'fecha_matricula', name='uq_matricula_est_mod_fecha')
    )
    op.create_table('solicitudes_tramite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_tramite', sa.String(length=100), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones_estudiante', sa.Text(), nullable=True),
    sa.Column('observaciones_admin', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('justificada', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('indicador_logro', sa.String(length=50), nullable=True),
    sa.Column('tipo_evaluacion', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programaciones_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=15), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('hora_fin > hora_inicio', name='ck_hora_fin_gt_inicio'),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salon_id'], ['salones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'salon_id', 'dia_semana', 'hora_inicio', name='uq_periodo_salon_horario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programaciones_clase')
    op.drop_table('calificaciones')
    op.drop_table('asistencias')
    op.drop_table('solicitudes_tramite')
    op.drop_table('matriculas')
    op.drop_table('estudiantes_info')
    op.drop_table('cursos')
    op.drop_table('modulos')
    op.drop_table('estudiantes')
    op.drop_table('docente')
    op.drop_table('administradores')
    op.drop_table('usuario')
    op.drop_table('salones')
    op.drop_table('programas')
    op.drop_table('periodos')
    # ### end Alembic commands ###
